### ISSUE TITLE
[ENHANCEMENT] Navigation bar and general overflow cut off

### ISSUE THREAD

**Issue by kwfk** [calblueprint/wecaresolar#71]
**Is your enhancement request related to a problem related to existing functionality or ux/ui? Please describe.**
This is a UI enhancement request where the navigation bar and `see all` buttons are cut off in the overflow.

**Describe the solution you'd like to see**
The width of the root page should use the device's view width so that all elements show up on the page without any cutoff.

**Additional context**
![image](https://user-images.githubusercontent.com/9738398/115130530-4cb0af80-9fa5-11eb-996b-746afd770985.png)

@susan-lin

**Comment by shannonbonet** [comment]
fixed!
