### ISSUE TITLE
[ENHANCEMENT] Troubleshoot page width overflow

### ISSUE THREAD

**Issue by kwfk** [calblueprint/wecaresolar#73]
**Is your enhancement request related to a problem related to existing functionality or ux/ui? Please describe.**
This is for UI enhancement.
The troubleshoot page is able to scroll horizontally when it doesn't seem like it should.

**Describe the solution you'd like to see**
The page width should match the device's view width so that there is no unnecessary scrolling.

**Additional context**
![image](https://user-images.githubusercontent.com/9738398/115130639-19baeb80-9fa6-11eb-90d2-1effad9cda45.png)

@susan-lin

**Comment by susan-lin** [comment]
Ty!! This should be fixed in master now!!
