### ISSUE TITLE
[ENHANCEMENT] Navigation bar at bottom of page in Troubleshoot page

### ISSUE THREAD

**Issue by kwfk** [calblueprint/wecaresolar#74]
**Is your enhancement request related to a problem related to existing functionality or ux/ui? Please describe.**
This a UI enhancement.
The navigation bar disappears because it is displayed at the bottom of the page only for the Troubleshoot page.

**Describe the solution you'd like to see**
The navigation bar should show up at the bottom of the device screen rather than the page, similarly to all the other pages.

**Additional context**
![image](https://user-images.githubusercontent.com/9738398/115130696-7e764600-9fa6-11eb-90a8-2e468d505edc.png)

@susan-lin

**Comment by susan-lin** [comment]
Ty!! This is now fixed in master!!
