### ISSUE TITLE
[ENHANCEMENT] Navigation bar in Troubleshoot page hides bottom cards

### ISSUE THREAD

**Issue by kwfk** [calblueprint/wecaresolar#75]
**Is your enhancement request related to a problem related to existing functionality or ux/ui? Please describe.**
This is a UI enhancement request.
The navigation bar is covering the bottom cards in the Troubleshoot page making it difficult to select those cards.

**Describe the solution you'd like to see**
The page should scroll further so that the navigation bar goes below the bottom cards and doesn't cover them.

**Additional context**
![image](https://user-images.githubusercontent.com/9738398/115130720-acf42100-9fa6-11eb-8015-290ed426cc22.png)

@susan-lin

**Comment by susan-lin** [comment]
ty!! should be fixed in master now
