### ISSUE TITLE
Troubleshoot tab changes the viewport height

### ISSUE THREAD

**Issue by ethanlee16** [calblueprint/wecaresolar#78]
**Describe the bug: What happened?**
The troubleshoot view content height is too large, which makes the tab bar disappear from its normal bottom-anchored position. It appears that the screen itself also exhibits some janky scrolling behavior, suggesting that `overflow: scroll` may be used in multiple places on this screen?

**url or screen that error occurred?**
Troubleshoot tab of app

**To Reproduce Bug**
1. Visit the Troubleshoot tab of the app.
2. Observe that the tab bar disappears from view, only navigable by scrolling down.

**Expected behavior?**
The tab bar stays in view when navigating to the Troubleshoot tab.

**Screenshots**
![image](https://user-images.githubusercontent.com/2977329/115163276-1afb1f80-a05d-11eb-8cae-10208c9c3ba9.png)

**Environment (please complete the following information):**
- production 

cc: @susan-lin

**Comment by susan-lin** [comment]
Ty!! Should be fixed in master now!
