### ISSUE TITLE
Filter by component should default to a fully empty selection

### ISSUE THREAD

**Issue by ethanlee16** [calblueprint/wecaresolar#79]
**Is your enhancement request related to a problem related to existing functionality or ux/ui? Please describe.**
When visiting the "Filter by" popover of the Favorites tab, the default state should be empty (nothing is selected).

This will allow the user to _additively_ select the types of content they want to see (rather than subtractively thinking about the content they don't want to see, or tapping "Deselect all" for both sections before filtering).

The empty state of the filter (fully unselected) already exhibits the correct functionality by showing everything.

**Describe the solution you'd like to see**
The default state of the "Filter by" component should have nothing selected, as shown below:

![image](https://user-images.githubusercontent.com/2977329/115163357-83e29780-a05d-11eb-90d0-32ecbb05e95b.png)

@susan-lin

**Comment by joyceyguo** [comment]
Thanks Ethan! Fixed :)
