### ISSUE TITLE
Report a Problem/Restart Troubleshooting buttons do nothing (Chrome Mobile)

### ISSUE THREAD

**Issue by ethanlee16** [calblueprint/wecaresolar#80]
**Describe the bug: What happened?**
"Report a Problem" and "Restart Troubleshooting" do nothing when tapped. Notably, this issue does not appear to be reproducible in Desktop Chrome.

**url or screen that error occurred?**
Troubleshooting screen, at this stage:

![image](https://user-images.githubusercontent.com/2977329/115163416-d2903180-a05d-11eb-9e90-cd6e623ef8cc.png)

**To Reproduce Bug**
(Visit on Chrome Mobile. I'm using a Galaxy Tab S2 on Chrome v76.)
1. Visit the Troubleshooting tab.
2. Tap a topic.
3. Tap "Yes, I do" at the prompt "Do you see an error code?"
4. Tap the Report a Problem button. Observe that nothing happens.
5. Tap the Restart Troubleshooting button. Observe that nothing happens.

**Expected behavior?**
I expect that the Restart Troubleshooting button would allow me to move back to the root question of the Troubleshooting flow. I'm not sure what Report a Problem is intended to do.

**Environment (please complete the following information):**
Which environment(s) is this bug located in?
- production

cc: @susan-lin

**Comment by susan-lin** [comment]
Ty!! This is now fixed in master through PR #69 !!
